'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property location() As Global.System.Drawing.Point
            Get
                Return CType(Me("location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property zoom() As Integer
            Get
                Return CType(Me("zoom"),Integer)
            End Get
            Set
                Me("zoom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property topmost() As Boolean
            Get
                Return CType(Me("topmost"),Boolean)
            End Get
            Set
                Me("topmost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property offset() As Global.System.Drawing.Point
            Get
                Return CType(Me("offset"),Global.System.Drawing.Point)
            End Get
            Set
                Me("offset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property hideMessage() As Boolean
            Get
                Return CType(Me("hideMessage"),Boolean)
            End Get
            Set
                Me("hideMessage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("800x600"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"900x675"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1000x750"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1100x825"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1200x900"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1300x975"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1400x1050"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1500x1125"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1"& _ 
            "600x1200"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1700x1275"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1800x1350"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2000x1500"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2400x1800"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2800x2100"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"3200x2400"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"3600"& _ 
            "x2700"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"4000x3000"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"4400x3300")>  _
        Public Property resolutions() As String
            Get
                Return CType(Me("resolutions"),String)
            End Get
            Set
                Me("resolutions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property links() As String
            Get
                Return CType(Me("links"),String)
            End Get
            Set
                Me("links") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MAINWNDMOAC | 䅍义乗䵄䅏C | MAINWNDASTONIA | SDL_app")>  _
        Public Property className() As String
            Get
                Return CType(Me("className"),String)
            End Get
            Set
                Me("className") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("moac | new | Knights of Astonia")>  _
        Public Property exe() As String
            Get
                Return CType(Me("exe"),String)
            End Get
            Set
                Me("exe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.0.0")>  _
        Public Property SettingsVersion() As String
            Get
                Return CType(Me("SettingsVersion"),String)
            End Get
            Set
                Me("SettingsVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property roundCorners() As Boolean
            Get
                Return CType(Me("roundCorners"),Boolean)
            End Get
            Set
                Me("roundCorners") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property gameOnOverview() As Boolean
            Get
                Return CType(Me("gameOnOverview"),Boolean)
            End Get
            Set
                Me("gameOnOverview") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SwitchToOverview() As Boolean
            Get
                Return CType(Me("SwitchToOverview"),Boolean)
            End Get
            Set
                Me("SwitchToOverview") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CycleAlt() As Boolean
            Get
                Return CType(Me("CycleAlt"),Boolean)
            End Get
            Set
                Me("CycleAlt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property StoCtrl() As Integer
            Get
                Return CType(Me("StoCtrl"),Integer)
            End Get
            Set
                Me("StoCtrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property StoAlt() As Integer
            Get
                Return CType(Me("StoAlt"),Integer)
            End Get
            Set
                Me("StoAlt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property StoShift() As Integer
            Get
                Return CType(Me("StoShift"),Integer)
            End Get
            Set
                Me("StoShift") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property CycleCtrlKeyFwd() As Integer
            Get
                Return CType(Me("CycleCtrlKeyFwd"),Integer)
            End Get
            Set
                Me("CycleCtrlKeyFwd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CycleAltKeyFwd() As Integer
            Get
                Return CType(Me("CycleAltKeyFwd"),Integer)
            End Get
            Set
                Me("CycleAltKeyFwd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property StoKey() As Integer
            Get
                Return CType(Me("StoKey"),Integer)
            End Get
            Set
                Me("StoKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("32")>  _
        Public Property CycleKeyFwd() As Integer
            Get
                Return CType(Me("CycleKeyFwd"),Integer)
            End Get
            Set
                Me("CycleKeyFwd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("32")>  _
        Public Property CycleKeyBwd() As Integer
            Get
                Return CType(Me("CycleKeyBwd"),Integer)
            End Get
            Set
                Me("CycleKeyBwd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CycleShiftKeyFwd() As Integer
            Get
                Return CType(Me("CycleShiftKeyFwd"),Integer)
            End Get
            Set
                Me("CycleShiftKeyFwd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property CycleShiftKeyBwd() As Integer
            Get
                Return CType(Me("CycleShiftKeyBwd"),Integer)
            End Get
            Set
                Me("CycleShiftKeyBwd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property CycleCtrlKeyBwd() As Integer
            Get
                Return CType(Me("CycleCtrlKeyBwd"),Integer)
            End Get
            Set
                Me("CycleCtrlKeyBwd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CycleAltKeyBwd() As Integer
            Get
                Return CType(Me("CycleAltKeyBwd"),Integer)
            End Get
            Set
                Me("CycleAltKeyBwd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CycleOnClose() As Boolean
            Get
                Return CType(Me("CycleOnClose"),Boolean)
            End Get
            Set
                Me("CycleOnClose") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Someone")>  _
        Public Property topSort() As String
            Get
                Return CType(Me("topSort"),String)
            End Get
            Set
                Me("topSort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Someone")>  _
        Public Property botSort() As String
            Get
                Return CType(Me("botSort"),String)
            End Get
            Set
                Me("botSort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Whitelist() As Boolean
            Get
                Return CType(Me("Whitelist"),Boolean)
            End Get
            Set
                Me("Whitelist") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SingleInstance() As Boolean
            Get
                Return CType(Me("SingleInstance"),Boolean)
            End Get
            Set
                Me("SingleInstance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LockEq() As Boolean
            Get
                Return CType(Me("LockEq"),Boolean)
            End Get
            Set
                Me("LockEq") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MaxBorderTop() As Integer
            Get
                Return CType(Me("MaxBorderTop"),Integer)
            End Get
            Set
                Me("MaxBorderTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MaxBorderLeft() As Integer
            Get
                Return CType(Me("MaxBorderLeft"),Integer)
            End Get
            Set
                Me("MaxBorderLeft") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MaxBorderRight() As Integer
            Get
                Return CType(Me("MaxBorderRight"),Integer)
            End Get
            Set
                Me("MaxBorderRight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MaxBorderBot() As Integer
            Get
                Return CType(Me("MaxBorderBot"),Integer)
            End Get
            Set
                Me("MaxBorderBot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ExtraMaxColRow() As Integer
            Get
                Return CType(Me("ExtraMaxColRow"),Integer)
            End Get
            Set
                Me("ExtraMaxColRow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property OneLessRowCol() As Boolean
            Get
                Return CType(Me("OneLessRowCol"),Boolean)
            End Get
            Set
                Me("OneLessRowCol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("900, 675")>  _
        Public Property resol() As Global.System.Drawing.Size
            Get
                Return CType(Me("resol"),Global.System.Drawing.Size)
            End Get
            Set
                Me("resol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DarkMode() As Boolean
            Get
                Return CType(Me("DarkMode"),Boolean)
            End Get
            Set
                Me("DarkMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScalingMode() As Integer
            Get
                Return CType(Me("ScalingMode"),Integer)
            End Get
            Set
                Me("ScalingMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CheckForUpdate() As Boolean
            Get
                Return CType(Me("CheckForUpdate"),Boolean)
            End Get
            Set
                Me("CheckForUpdate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StartMaximized() As Boolean
            Get
                Return CType(Me("StartMaximized"),Boolean)
            End Get
            Set
                Me("StartMaximized") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SizingBorder() As Boolean
            Get
                Return CType(Me("SizingBorder"),Boolean)
            End Get
            Set
                Me("SizingBorder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MinMin() As Boolean
            Get
                Return CType(Me("MinMin"),Boolean)
            End Get
            Set
                Me("MinMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CloseAll() As Boolean
            Get
                Return CType(Me("CloseAll"),Boolean)
            End Get
            Set
                Me("CloseAll") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property CloseAllCtrl() As Integer
            Get
                Return CType(Me("CloseAllCtrl"),Integer)
            End Get
            Set
                Me("CloseAllCtrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property CloseAllShift() As Integer
            Get
                Return CType(Me("CloseAllShift"),Integer)
            End Get
            Set
                Me("CloseAllShift") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CloseAllAlt() As Integer
            Get
                Return CType(Me("CloseAllAlt"),Integer)
            End Get
            Set
                Me("CloseAllAlt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("123")>  _
        Public Property CloseAllKey() As Integer
            Get
                Return CType(Me("CloseAllKey"),Integer)
            End Get
            Set
                Me("CloseAllKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Theme() As Integer
            Get
                Return CType(Me("Theme"),Integer)
            End Get
            Set
                Me("Theme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property remeberSettingsTab() As Integer
            Get
                Return CType(Me("remeberSettingsTab"),Integer)
            End Get
            Set
                Me("remeberSettingsTab") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QLShowHidden() As Boolean
            Get
                Return CType(Me("QLShowHidden"),Boolean)
            End Get
            Set
                Me("QLShowHidden") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HoverActivate() As Boolean
            Get
                Return CType(Me("HoverActivate"),Boolean)
            End Get
            Set
                Me("HoverActivate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowEnd() As Boolean
            Get
                Return CType(Me("ShowEnd"),Boolean)
            End Get
            Set
                Me("ShowEnd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ToggleTop() As Boolean
            Get
                Return CType(Me("ToggleTop"),Boolean)
            End Get
            Set
                Me("ToggleTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TogTopAlt() As Integer
            Get
                Return CType(Me("TogTopAlt"),Integer)
            End Get
            Set
                Me("TogTopAlt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property TogTopCtrl() As Integer
            Get
                Return CType(Me("TogTopCtrl"),Integer)
            End Get
            Set
                Me("TogTopCtrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TogTopShift() As Integer
            Get
                Return CType(Me("TogTopShift"),Integer)
            End Get
            Set
                Me("TogTopShift") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property TogTopWin() As Integer
            Get
                Return CType(Me("TogTopWin"),Integer)
            End Get
            Set
                Me("TogTopWin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property StoWin() As Integer
            Get
                Return CType(Me("StoWin"),Integer)
            End Get
            Set
                Me("StoWin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CycleWinKeyFwd() As Integer
            Get
                Return CType(Me("CycleWinKeyFwd"),Integer)
            End Get
            Set
                Me("CycleWinKeyFwd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CycleWinKeyBwd() As Integer
            Get
                Return CType(Me("CycleWinKeyBwd"),Integer)
            End Get
            Set
                Me("CycleWinKeyBwd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CloseAllWin() As Integer
            Get
                Return CType(Me("CloseAllWin"),Integer)
            End Get
            Set
                Me("CloseAllWin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("84")>  _
        Public Property ToggleTopKey() As Integer
            Get
                Return CType(Me("ToggleTopKey"),Integer)
            End Get
            Set
                Me("ToggleTopKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property KeepOnOverview() As Boolean
            Get
                Return CType(Me("KeepOnOverview"),Boolean)
            End Get
            Set
                Me("KeepOnOverview") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property AlterOverviewPlusCtrl() As Integer
            Get
                Return CType(Me("AlterOverviewPlusCtrl"),Integer)
            End Get
            Set
                Me("AlterOverviewPlusCtrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AlterOverviewPlusWin() As Integer
            Get
                Return CType(Me("AlterOverviewPlusWin"),Integer)
            End Get
            Set
                Me("AlterOverviewPlusWin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AlterOverviewPlusShift() As Integer
            Get
                Return CType(Me("AlterOverviewPlusShift"),Integer)
            End Get
            Set
                Me("AlterOverviewPlusShift") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AlterOverviewPlusAlt() As Integer
            Get
                Return CType(Me("AlterOverviewPlusAlt"),Integer)
            End Get
            Set
                Me("AlterOverviewPlusAlt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("107")>  _
        Public Property AlterOverviewPlusKey() As Integer
            Get
                Return CType(Me("AlterOverviewPlusKey"),Integer)
            End Get
            Set
                Me("AlterOverviewPlusKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property AlterOverviewMinCtrl() As Integer
            Get
                Return CType(Me("AlterOverviewMinCtrl"),Integer)
            End Get
            Set
                Me("AlterOverviewMinCtrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AlterOverviewMinWin() As Integer
            Get
                Return CType(Me("AlterOverviewMinWin"),Integer)
            End Get
            Set
                Me("AlterOverviewMinWin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AlterOverviewMinShift() As Integer
            Get
                Return CType(Me("AlterOverviewMinShift"),Integer)
            End Get
            Set
                Me("AlterOverviewMinShift") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AlterOverviewMinAlt() As Integer
            Get
                Return CType(Me("AlterOverviewMinAlt"),Integer)
            End Get
            Set
                Me("AlterOverviewMinAlt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("109")>  _
        Public Property AlterOverviewMinKey() As Integer
            Get
                Return CType(Me("AlterOverviewMinKey"),Integer)
            End Get
            Set
                Me("AlterOverviewMinKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property AlterOverviewStarCtrl() As Integer
            Get
                Return CType(Me("AlterOverviewStarCtrl"),Integer)
            End Get
            Set
                Me("AlterOverviewStarCtrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AlterOverviewStarWin() As Integer
            Get
                Return CType(Me("AlterOverviewStarWin"),Integer)
            End Get
            Set
                Me("AlterOverviewStarWin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AlterOverviewStarShift() As Integer
            Get
                Return CType(Me("AlterOverviewStarShift"),Integer)
            End Get
            Set
                Me("AlterOverviewStarShift") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AlterOverviewStarAlt() As Integer
            Get
                Return CType(Me("AlterOverviewStarAlt"),Integer)
            End Get
            Set
                Me("AlterOverviewStarAlt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("106")>  _
        Public Property AlterOverviewStarKey() As Integer
            Get
                Return CType(Me("AlterOverviewStarKey"),Integer)
            End Get
            Set
                Me("AlterOverviewStarKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AlterOverview() As Boolean
            Get
                Return CType(Me("AlterOverview"),Boolean)
            End Get
            Set
                Me("AlterOverview") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ApplyAlterNormal() As Boolean
            Get
                Return CType(Me("ApplyAlterNormal"),Boolean)
            End Get
            Set
                Me("ApplyAlterNormal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MaxNormOverview() As Boolean
            Get
                Return CType(Me("MaxNormOverview"),Boolean)
            End Get
            Set
                Me("MaxNormOverview") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ScalA.My.MySettings
            Get
                Return Global.ScalA.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
